  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"
  
  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"
  
  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"


   [[main]]
  name = "CV"
  weight = 400
  identifier = "cv"
  url = "cv/Mikail_Kurt_CV.pdf"
  
  [[main]]
  name = "Location"
  weight = 400
  identifier = "location"
  url = "location/location.Rmd"
